<?php
  return array(
    'Agriculture & Farming',
    'Arts & Heritage Crafts',
    'Banking, Finance and Insurance',
    'Charity & Philanthropy',
    'Disaster Relief',
    'Economy',
    'Education',
    'Elections & Governance',
    'Emergency Response',
    'Environment, Forestry & Wildlife Conservation',
    'Fisheries & Aquatic Resources',
    'Foreign Affairs',
    'Health, Nutrition & Indigenous Medicine',
    'Inland Revenue & Taxes',
    'Justice, Legal & Legislation',
    'Labor',
    'Land',
    'Law Enforcement & Defence',
    'Local Government & Provincial Councils',
    'Manufacturing',
    'Media & Communications',
    'Official Languages',
    'Open Data',
    'Pensions, Social Security & Welfare',
    'Ports & Shipping',
    'Power & Energy',
    'Productivity Tools',
    'Public administration',
    'Public Utilities',
    'Real estate, Housing, Construction',
    'Right to Information',
    'Roads, Highways, Infrastructure',
    'Science, Technology & Research',
    'Sports',
    'Telecommunications',
    'Transportation',
    'Travel & Tourism',
    'Waste Management & Disposal',
    'Women & Children'
  );
?>